create database products_catalog;

create user db_admin with password 'db_admin';
alter database products_catalog owner to db_admin;
alter user db_admin with superuser;

grant all privileges on database products_catalog to db_admin;

create table categories
(
    id            smallint GENERATED BY DEFAULT AS IDENTITY not null
        primary key,
    category_name varchar(32)
);

create table products
(
    id           smallint GENERATED BY DEFAULT AS IDENTITY not null
        primary key,
    product_name varchar(32),
    description  varchar(64),
    price        numeric(7, 3),
    general_note varchar(64),
    special_note varchar(64),
    category_id  smallint references categories (id)
);


create table roles
(
    id        smallint GENERATED BY DEFAULT AS IDENTITY not null
        primary key,
    role_name varchar(32)
);

create table users
(
    id       smallint GENERATED BY DEFAULT AS IDENTITY    not null
        primary key,
    email    varchar(255) not null
        unique,
    password varchar(255) not null,

    role_id  smallint default 1
        references roles
);

insert into roles (role_name) values
                      ('simple_user');
insert into roles (role_name) values
                      ('advanced_user');
insert into roles (role_name) values
                      ('admin');


insert into categories (category_name) values
                                           ('Еда');
insert into categories (category_name) values
                                           ('Вкусности');
insert into categories (category_name) values
                                           ('Вода');


insert into products (product_name, description, price, general_note, special_note, category_id) values
('Селедка', 'Селедка соленая', 10.000, 'Акция', 'Пересоленая', 1);
insert into products (product_name, description, price, general_note, special_note, category_id) values
('Тушенка', 'Тушенка говяжая', 20.000, 'Вкусная', 'Жилы', 1);
insert into products (product_name, description, price, general_note, special_note, category_id) values
('Сгущенка', 'В банках', 30.000, 'С ключом', 'Вкусная', 2);
insert into products (product_name, description, price, general_note, special_note, category_id) values
('Квас', 'В бутылках', 15.000, 'Вятский', 'Теплый', 3);